version: "3.9"
services:
  web:
    build: ./app
    links:
      - db
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: rmn
      MYSQL_PASSWORD: password
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
    ports:
      - "3320:3306"
  tests:
    build: ./app
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
      - ./app:/app
    command: ["pytest"]